BS = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils"]
BSS = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils"]
BS_CRD = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils", "components"]
BS_LBD = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils", "components"]
REL_DIAG = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils", "classes", "axes"]
CRPS_FROM_BS = ["entités", "échéances", "sous-ensembles", "échantillons"]
CRPS_FROM_ECDF = ["entités", "échéances", "sous-ensembles", "échantillons"]
QS = ["entités", "échéances", "sous-ensembles", "échantillons", "quantiles"]
CRPS_FROM_QS = ["entités", "échéances", "sous-ensembles", "échantillons"]
CONT_TBL = ["entités", "échéances", "sous-ensembles", "échantillons", "niveaux", "seuils", "cellules"]
POD = ["entités", "échéances", "sous-ensembles", "échantillons", "niveaux", "seuils"]
POFD = ["entités", "échéances", "sous-ensembles", "échantillons", "niveaux", "seuils"]
FAR = ["entités", "échéances", "sous-ensembles", "échantillons", "niveaux", "seuils"]
CSI = ["entités", "échéances", "sous-ensembles", "échantillons", "niveaux", "seuils"]
ROCSS = ["entités", "échéances", "sous-ensembles", "échantillons", "seuils"]
RANK_HIST = ["entités", "échéances", "sous-ensembles", "échantillons", "rangs"]
DS = ["entités", "échéances", "sous-ensembles", "échantillons"]
AS = ["entités", "échéances", "sous-ensembles", "échantillons"]
CR = ["entités", "échéances", "sous-ensembles", "échantillons", "intervalles"]
AW = ["entités", "échéances", "sous-ensembles", "échantillons", "intervalles"]
AWN = ["entités", "échéances", "sous-ensembles", "échantillons", "intervalles"]
WS = ["entités", "échéances", "sous-ensembles", "échantillons", "intervalles"]
ES = ["toutes entités", "échéances", "sous-ensembles", "échantillons"]
