MAE = ["entités", "sous-ensembles", "échantillons"]
MARE = ["entités", "sous-ensembles", "échantillons"]
MSE = ["entités", "sous-ensembles", "échantillons"]
RMSE = ["entités", "sous-ensembles", "échantillons"]
NSE = ["entités", "sous-ensembles", "échantillons"]
KGE = ["entités", "sous-ensembles", "échantillons"]
KGE_D = ["entités", "sous-ensembles", "échantillons", "composantes"]
KGEPRIME = ["entités", "sous-ensembles", "échantillons"]
KGEPRIME_D = ["entités", "sous-ensembles", "échantillons", "composantes"]
KGENP = ["entités", "sous-ensembles", "échantillons"]
KGENP_D = ["entités", "sous-ensembles", "échantillons", "composantes"]
CONT_TBL = ["entités", "sous-ensembles", "échantillons", "cellules"]
completeness = ["entités", "sous-ensembles", "échantillons"]
