BS = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils"]
BSS = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils"]
BS_CRD = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils", "composantes"]
BS_LBD = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils", "composantes"]
REL_DIAG = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils", "classes", "axes"]
CRPS_FROM_BS = ["entites", "echeances", "sous_ensembles", "echantillons"]
CRPS_FROM_ECDF = ["entites", "echeances", "sous_ensembles", "echantillons"]
QS = ["entites", "echeances", "sous_ensembles", "echantillons", "quantiles"]
CRPS_FROM_QS = ["entites", "echeances", "sous_ensembles", "echantillons"]
CONT_TBL = ["entites", "echeances", "sous_ensembles", "echantillons", "niveaux", "seuils", "cellules"]
POD = ["entites", "echeances", "sous_ensembles", "echantillons", "niveaux", "seuils"]
POFD = ["entites", "echeances", "sous_ensembles", "echantillons", "niveaux", "seuils"]
FAR = ["entites", "echeances", "sous_ensembles", "echantillons", "niveaux", "seuils"]
CSI = ["entites", "echeances", "sous_ensembles", "echantillons", "niveaux", "seuils"]
ROCSS = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils"]
RANK_HIST = ["entites", "echeances", "sous_ensembles", "echantillons", "rangs"]
DS = ["entites", "echeances", "sous_ensembles", "echantillons"]
AS = ["entites", "echeances", "sous_ensembles", "echantillons"]
CR = ["entites", "echeances", "sous_ensembles", "echantillons", "intervalles"]
AW = ["entites", "echeances", "sous_ensembles", "echantillons", "intervalles"]
AWN = ["entites", "echeances", "sous_ensembles", "echantillons", "intervalles"]
WS = ["entites", "echeances", "sous_ensembles", "echantillons", "intervalles"]
ES = ["toutes_entites", "echeances", "sous_ensembles", "echantillons"]
completeness = ["entites", "echeances", "sous_ensembles", "echantillons"]
