MAE = ["echeances", "sous_ensembles", "échantillons"]
MARE = ["echeances", "sous_ensembles", "échantillons"]
MSE = ["echeances", "sous_ensembles", "échantillons"]
RMSE = ["echeances", "sous_ensembles", "échantillons"]
NSE = ["echeances", "sous_ensembles", "échantillons"]
KGE = ["echeances", "sous_ensembles", "échantillons"]
KGE_D = ["echeances", "sous_ensembles", "échantillons", "composantes"]
KGEPRIME = ["echeances", "sous_ensembles", "échantillons"]
KGEPRIME_D = ["echeances", "sous_ensembles", "échantillons", "composantes"]
KGENP = ["echeances", "sous_ensembles", "échantillons"]
KGENP_D = ["echeances", "sous_ensembles", "échantillons", "composantes"]
CONT_TBL = ["echeances", "sous_ensembles", "échantillons", "seuils", "cellules"]
completeness = ["echeances", "sous_ensembles", "echantillons"]
