MAE = ["entites", "echeances", "sous_ensembles", "echantillons"]
MARE = ["entites", "echeances", "sous_ensembles", "echantillons"]
MSE = ["entites", "echeances", "sous_ensembles", "echantillons"]
RMSE = ["entites", "echeances", "sous_ensembles", "echantillons"]
NSE = ["entites", "echeances", "sous_ensembles", "echantillons"]
KGE = ["entites", "echeances", "sous_ensembles", "echantillons"]
KGE_D = ["entites", "echeances", "sous_ensembles", "echantillons", "composantes"]
KGEPRIME = ["entites", "echeances", "sous_ensembles", "echantillons"]
KGEPRIME_D = ["entites", "echeances", "sous_ensembles", "echantillons", "composantes"]
KGENP = ["entites", "echeances", "sous_ensembles", "echantillons"]
KGENP_D = ["entites", "echeances", "sous_ensembles", "echantillons", "composantes"]
CONT_TBL = ["entites", "echeances", "sous_ensembles", "echantillons", "seuils", "cellules"]
completeness = ["entites", "echeances", "sous_ensembles", "echantillons"]
