BS = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil"]
BSS = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil"]
BS_CRD = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil", "composante"]
BS_LBD = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil", "composante"]
REL_DIAG = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil", "classe", "axe"]
CRPS_FROM_BS = ["entite", "echeance", "sous_ensemble", "echantillon"]
CRPS_FROM_ECDF = ["entite", "echeance", "sous_ensemble", "echantillon"]
QS = ["entite", "echeance", "sous_ensemble", "echantillon", "quantile"]
CRPS_FROM_QS = ["entite", "echeance", "sous_ensemble", "echantillon"]
CONT_TBL = ["entite", "echeance", "sous_ensemble", "echantillon", "niveau", "seuil", "cellule"]
POD = ["entite", "echeance", "sous_ensemble", "echantillon", "niveau", "seuil"]
POFD = ["entite", "echeance", "sous_ensemble", "echantillon", "niveau", "seuil"]
FAR = ["entite", "echeance", "sous_ensemble", "echantillon", "niveau", "seuil"]
CSI = ["entite", "echeance", "sous_ensemble", "echantillon", "niveau", "seuil"]
ROCSS = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil"]
RANK_HIST = ["entite", "echeance", "sous_ensemble", "echantillon", "rang"]
DS = ["entite", "echeance", "sous_ensemble", "echantillon"]
AS = ["entite", "echeance", "sous_ensemble", "echantillon"]
CR = ["entite", "echeance", "sous_ensemble", "echantillon", "intervalle"]
AW = ["entite", "echeance", "sous_ensemble", "echantillon", "intervalle"]
AWN = ["entite", "echeance", "sous_ensemble", "echantillon", "intervalle"]
WS = ["entite", "echeance", "sous_ensemble", "echantillon", "intervalle"]
ES = ["toutes_entite", "echeance", "sous_ensemble", "echantillon"]
completeness = ["entite", "echeance", "sous_ensemble", "echantillon"]
