MAE = ["entite", "echeance", "sous_ensemble", "echantillon"]
MARE = ["entite", "echeance", "sous_ensemble", "echantillon"]
MSE = ["entite", "echeance", "sous_ensemble", "echantillon"]
RMSE = ["entite", "echeance", "sous_ensemble", "echantillon"]
NSE = ["entite", "echeance", "sous_ensemble", "echantillon"]
KGE = ["entite", "echeance", "sous_ensemble", "echantillon"]
KGE_D = ["entite", "echeance", "sous_ensemble", "echantillon", "composante"]
KGEPRIME = ["entite", "echeance", "sous_ensemble", "echantillon"]
KGEPRIME_D = ["entite", "echeance", "sous_ensemble", "echantillon", "composante"]
KGENP = ["entite", "echeance", "sous_ensemble", "echantillon"]
KGENP_D = ["entite", "echeance", "sous_ensemble", "echantillon", "composante"]
CONT_TBL = ["entite", "echeance", "sous_ensemble", "echantillon", "seuil", "cellule"]
completeness = ["entite", "echeance", "sous_ensemble", "echantillon"]
